### ISSUE TITLE
python package

### ISSUE THREAD

**Issue by GSI** [pstiasny/VITABS#2]
Interesting project!

Would you mind making a package so that the software may be installed with **pip** ?

**Comment by pstiasny** [comment]
Good idea, I'll take care of that.

**Comment by pstiasny** [comment]
The package is now available [via PyPI](https://pypi.python.org/pypi/vitabs/).

**Comment by GSI** [comment]
Cool.

Just getting this error:

```
# pipsi install vitabs
Running virtualenv with interpreter /usr/bin/python
Using base prefix '/usr'
New python executable in /home/gsi/.local/venvs/vitabs/bin/python
Installing setuptools, pip, wheel...done.
Collecting vitabs
Installing collected packages: vitabs
Successfully installed vitabs-0.1
  Linked script /home/gsi/.local/bin/vitabs
Done.

# vitabs
    print "\033[91mSomething terrible happened\033[0m"
                                                     ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by pstiasny** [comment]
Python 3 is not currently supported. You need to use pip that's appropriate for your Python 2 installation.

**Comment by GSI** [comment]
Ah! Thanks. Done:

`pipsi install --python python2 vitabs`

Eager to check out the app;
